// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProjectTest
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProjectTest.114f0d03-8be6-44dd-af4d-f3a4702cfd31";
        public const string Name = "VSIXProjectTest";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Ömer Özkurt";
        public const string Tags = "";
    }
}
