// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace VSIXProjectTest
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSIXProjectTestString = "ce1dce7a-dbc5-4c3a-8172-5ce4dc98f12b";
        public static Guid VSIXProjectTest = new Guid(VSIXProjectTestString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
    }
}